version: '3.1'

services:
  serv:
    container_name: serv
    build: ./serv
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - serv/.env
    depends_on:
      - db
    command: sh ./serv/docker-entrypoint.sh
  db:
    image: postgres
#    restart: always
    env_file:
      - ./serv/.env
    ports:
      - "5433:5432"
    volumes:
      - trainee_volume:/var/lib/postgresql/data

volumes:
  trainee_volume:
    driver: local