version: '3.1'

services:
  serv:
    container_name: serv
    build: ./serv
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - serv/.env
    depends_on:
      - db
    command: sh ./serv/docker-entrypoint.sh
#      - "python3 manage.py migrate"
#      - "python3 manage.py runserver 127.0.0.1:8000"
  db:
    image: postgres
    restart: always
    env_file:
      - ./serv/.env
    ports:
      - "5433:5432"
