# Generated by Django 3.2 on 2022-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Производитель')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('engine_v', models.FloatField(verbose_name='Объем двигателя')),
                ('car_body', models.CharField(choices=[('SE', 'Sedan'), ('CO', 'Coupe'), ('SC', 'Sports car'), ('SW', 'Station wagon'), ('HB', 'Hatchback'), ('CT', 'Convertible'), ('SUV', 'Sport-Utility vehicle'), ('MV', 'Minivan'), ('PUT', 'Pick-up truck')], max_length=20, verbose_name='Тип кузова')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarPriceRelationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('price_with_discount', models.FloatField(default=None, null=True, verbose_name='Цена со скидкой')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['supplier', 'car'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomSupplierOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', 'showroom'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название поставщика')),
                ('date_founded', models.DateField(verbose_name='Дата основания')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
