# Generated by Django 4.1 on 2022-08-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("carshowroom", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=20, verbose_name="Производитель"),
                ),
                ("model", models.CharField(max_length=20, verbose_name="Модель")),
                ("color", models.CharField(max_length=20, verbose_name="Цвет")),
                ("engine_v", models.FloatField(verbose_name="Объем двигателя")),
                (
                    "car_body",
                    models.CharField(
                        choices=[
                            ("SE", "Sedan"),
                            ("CO", "Coupe"),
                            ("SC", "Sports car"),
                            ("SW", "Station wagon"),
                            ("HB", "Hatchback"),
                            ("CT", "Convertible"),
                            ("SUV", "Sport-Utility vehicle"),
                            ("MV", "Minivan"),
                            ("PUT", "Pick-up truck"),
                        ],
                        max_length=20,
                        verbose_name="Тип кузова",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Название поставщика"),
                ),
                ("date_founded", models.DateField(verbose_name="Дата основания")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomSupplierOffers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "showroom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carshowroom.carshowroom",
                        verbose_name="Автосалон",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={"ordering": ["-date", "showroom"]},
        ),
        migrations.CreateModel(
            name="CarPriceRelationSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={"ordering": ["supplier", "car"]},
        ),
    ]
