# Generated by Django 3.2 on 2022-10-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carshowroom', '0003_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showroomsupplieroffers',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='supplier.car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='showroomsupplieroffers',
            name='showroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carshowroom.carshowroom', verbose_name='Автосалон'),
        ),
        migrations.AddField(
            model_name='showroomsupplieroffers',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='carpricerelationsupplier',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_car_prices', to='supplier.car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='carpricerelationsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'color', 'engine_v', 'car_body')},
        ),
        migrations.AlterUniqueTogether(
            name='carpricerelationsupplier',
            unique_together={('car', 'supplier')},
        ),
    ]
