# Generated by Django 3.2 on 2022-08-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_carpricerelationsupplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricerelationsupplier',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_car_prices', to='supplier.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='carpricerelationsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_prices', to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
