# Generated by Django 3.2 on 2022-10-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0006_auto_20221006_1427'),
        ('supplier', '0004_alter_carpricerelationsupplier_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomsupplieroffers',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='showroomsupplieroffers',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carshowroom.carshowroom', verbose_name='Автосалон'),
        ),
        migrations.AlterField(
            model_name='showroomsupplieroffers',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='Поставщик'),
        ),
    ]
