# Generated by Django 3.2 on 2022-10-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carshowroom', '0001_initial'),
        ('supplier', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdiscount',
            name='discounted_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='supplier.carpricerelationsupplier'),
        ),
        migrations.AddField(
            model_name='carshowroomdiscount',
            name='discounted_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='carshowroom.carpricerelationshowroom'),
        ),
    ]
