# Generated by Django 4.1 on 2022-08-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
        ("carshowroom", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customershowroomoffers",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier.car",
                verbose_name="Автомобиль",
            ),
        ),
        migrations.AddField(
            model_name="customershowroomoffers",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="customer.customer",
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="customershowroomoffers",
            name="showroom",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="carshowroom.carshowroom",
                verbose_name="Автосалон",
            ),
        ),
        migrations.AddField(
            model_name="carpricerelationshowroom",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.car",
                verbose_name="Автомобиль",
            ),
        ),
        migrations.AddField(
            model_name="carpricerelationshowroom",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="carshowroom.carshowroom",
                verbose_name="Автосалон",
            ),
        ),
    ]
