# Generated by Django 3.2 on 2022-10-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
        ('carshowroom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowroom',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpricerelationshowroom',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carshowroom_car_prices', to='supplier.car', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='carpricerelationshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carshowroom.carshowroom', verbose_name='Автосалон'),
        ),
        migrations.AlterUniqueTogether(
            name='carpricerelationshowroom',
            unique_together={('showroom', 'car')},
        ),
    ]
