# Generated by Django 3.2 on 2022-08-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('carshowroom', '0003_alter_carpricerelationshowroom_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershowroomoffers',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='customer.customer', verbose_name='Покупатель'),
        ),
    ]
