# Generated by Django 3.2 on 2022-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0004_alter_carpricerelationshowroom_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricerelationshowroom',
            name='price_with_discount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
