# Generated by Django 3.2 on 2022-08-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20220819_1421'),
        ('carshowroom', '0004_alter_customershowroomoffers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricerelationshowroom',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carshowroom_car_prices', to='supplier.car', verbose_name='Автомобиль'),
        ),
    ]
