# Generated by Django 3.2 on 2022-08-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0005_alter_carpricerelationshowroom_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricerelationshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_prices', to='carshowroom.carshowroom', verbose_name='Автосалон'),
        ),
    ]
