# Generated by Django 3.2 on 2022-09-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0006_alter_carpricerelationshowroom_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpricerelationshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carshowroom.carshowroom', verbose_name='Автосалон'),
        ),
    ]
