# Generated by Django 4.1 on 2022-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                ("surname", models.CharField(max_length=20, verbose_name="Фамилия")),
                ("balance", models.FloatField(verbose_name="Баланс")),
                ("is_active", models.BooleanField(default=True)),
            ],
        )
    ]
